# Generated by Django 2.2.4 on 2019-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('ranking', models.IntegerField()),
                ('metadata', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField()),
                ('audit_log', models.CharField(max_length=30)),
            ],
        ),
    ]
