# Generated by Django 2.2.4 on 2019-08-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='metadata',
            field=models.TextField(blank=True),
        ),
    ]
