# Generated by Django 2.2.4 on 2019-08-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190815_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('old_values', models.TextField()),
                ('new_values', models.TextField()),
                ('url', models.URLField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tracker',
            name='audit_log',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
