# Generated by Django 2.2.4 on 2019-08-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190815_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='audit_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_tracker', to='tracker.AuditLog'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
