# Generated by Django 2.2.4 on 2019-08-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='audit_log',
        ),
    ]
