# Generated by Django 2.2.4 on 2019-08-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_tracker_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='record_id',
            field=models.IntegerField(default=0),
        ),
    ]
