# Generated by Django 2.2.4 on 2019-08-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auditlog_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='ranking',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Ranking_Category_Relationship',
        ),
    ]
