# Generated by Django 2.2.4 on 2019-08-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20190816_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='model',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
